spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    pknu.vcd: trace
    org.springframework.security: debug
    org.springframework.orm.jpa: debug
    org.springframework.orm.transaction: debug
    org.hibernate.orm.jdbc.bind: trace

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    bucketName: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION} # ap-northeast-2