spring.application.name: pknu-vcd-server
spring.profiles.active: local

spring:
  jpa:
    open-in-view: false

---
spring.config.activate.on-profile: local

spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET}
    endpoint: ${AWS_S3_ENDPOINT}
    region: ${AWS_S3_REGION}

---
spring.config.activate.on-profile: prod

spring:
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET}
    endpoint: ${AWS_S3_ENDPOINT}
    region: ${AWS_S3_REGION}